# Generated by Django 3.2.9 on 2023-03-28 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_guest',
        ),
    ]
