# Generated by Django 4.1 on 2022-09-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_shippinginformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginformation',
            name='address',
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='apartment_suite_building',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='city_town_area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='street_lane_other',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
